version: '2.1'  # Balena supports version 2.1 of the Docker Compose spec
services:
  talker:
    build: .
    network_mode: host
    command: ros2 run demo_nodes_cpp talker
  ros2router:
    image: husarnet/ros2router:1.9.0
    network_mode: host
    depends_on:
      husarnet:
        condition: service_started
    environment:
      - EXIT_IF_HOST_TABLE_CHANGED=TRUE
      - PARTICIPANTS=husarnet,if-eth0
  husarnet:
    image: husarnet/husarnet:2.0.180
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun'
    environment:
      - HOSTNAME=duke-rpi-host
      - JOINCODE
      - WAIT_HOSTNAMES=duke-rpi-host, operator-host

